# Generated by Django 4.2 on 2023-04-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password2',
        ),
    ]
