# Generated by Django 4.2 on 2023-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_password1_employee_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('ward_no', models.IntegerField()),
                ('village', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('booth_num', models.CharField(max_length=100)),
                ('voter_id', models.CharField(max_length=15)),
                ('volunteer', models.CharField(max_length=5)),
                ('contribution', models.CharField(max_length=100)),
                ('member_bio', models.TextField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
