# Generated by Django 4.2 on 2023-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_member_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='ward_no',
            field=models.CharField(max_length=5),
        ),
    ]
