# Generated by Django 4.2 on 2023-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_member_address_alter_member_member_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='booth_num',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='village',
        ),
        migrations.RemoveField(
            model_name='member',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='member',
            name='voter_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ward_no',
        ),
        migrations.AddField(
            model_name='member',
            name='aadhaar',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='area',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pinCode',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sanstha_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
