# Generated by Django 4.2 on 2023-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rename_image_member_photo_remove_member_booth_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default='deactive', max_length=50, null=True),
        ),
    ]
