# Generated by Django 4.2 on 2023-05-02 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_member_name_alter_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
