# Generated by Django 4.2 on 2023-05-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_member_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_story',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
