# Generated by Django 4.2 on 2023-05-03 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_member_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_story',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
