# Generated by Django 4.2 on 2023-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_member_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_story',
            name='title',
            field=models.CharField(blank='True', default='', max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
