# Generated by Django 4.2 on 2023-05-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_member_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_story',
            name='title',
        ),
    ]
