# Generated by Django 4.2 on 2023-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_remove_member_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_story',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='member_story',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='member_story',
            name='content',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
