# Generated by Django 4.2 on 2023-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_member_story_file_member_story_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_story',
            name='status',
            field=models.CharField(blank=True, default='Deactive', max_length=10, null=True),
        ),
    ]
