# Generated by Django 4.2 on 2023-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_member_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default='Deactive', max_length=50, null=True),
        ),
    ]
