# Generated by Django 4.2 on 2023-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_donation_futureevent_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('content', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='member_story',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member_story',
            name='user_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='member_story',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
