# Generated by Django 4.2 on 2023-05-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_admin_story_member_story_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_story',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='admin_story',
            name='user_name',
        ),
    ]
