# Generated by Django 4.2 on 2023-05-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_remove_admin_story_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
