# Generated by Django 4.2 on 2023-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
