# Generated by Django 4.2 on 2023-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
