# Generated by Django 4.2 on 2023-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_test_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date1',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
