# Generated by Django 4.2 on 2023-05-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_alter_test_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='date',
            new_name='date2',
        ),
    ]
