# Generated by Django 4.2 on 2023-05-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_rename_date_test_date2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
