# Generated by Django 4.2 on 2023-05-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_alter_admin_story_date_alter_member_story_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='date',
        ),
    ]
