# Generated by Django 4.2 on 2023-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_rename_created_at_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
