# Generated by Django 4.2 on 2023-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_alter_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='member_id',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
