# Generated by Django 4.2 on 2023-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_donation_member_id_donation_name_donation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='member_id',
            field=models.IntegerField(default=''),
        ),
    ]
