# Generated by Django 4.2 on 2023-05-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_alter_donation_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='member_id',
        ),
    ]
