# Generated by Django 4.2 on 2023-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_remove_donation_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('like_count', models.IntegerField(verbose_name=0)),
            ],
        ),
    ]
