# Generated by Django 4.2 on 2023-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_comment_section_like_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_section',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
