# Generated by Django 4.2 on 2023-05-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_alter_like_section_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like_Section',
        ),
        migrations.AddField(
            model_name='admin_story',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member_story',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
