# Generated by Django 4.2 on 2023-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_delete_like_section_admin_story_like_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_SectionMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
