# Generated by Django 4.2 on 2023-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_comment_sectionmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_story',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member_story',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
