# Generated by Django 4.2 on 2023-05-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_alter_admin_story_date_alter_donation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pustika',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
    ]
