# Generated by Django 4.2 on 2023-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_pustika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Login_Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
