# Generated by Django 4.2 on 2023-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_member_login_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_For_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
